
  Exclude:
    - 'Gemfile'

# Offense count: 2
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, IndentationWidth.
# SupportedStyles: outdent, indent
Layout/AccessModifierIndentation:
  Exclude:
    - 'app/controllers/application_controller.rb'
    - 'app/controllers/posts_controller.rb'

# Offense count: 2
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, IndentationWidth.
# SupportedStyles: with_first_argument, with_fixed_indentation
Layout/ArgumentAlignment:
  Exclude:
    - 'config/application.rb'
    - 'config/routes.rb'

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyleAlignWith.
# SupportedStylesAlignWith: either, start_of_block, start_of_line
Layout/BlockAlignment:
  Exclude:
    - 'spec/spec_helper.rb'

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle.
# SupportedStyles: leading, trailing
Layout/DotPosition:
  Exclude:
    - 'app/controllers/chat_controller.rb'

# Offense count: 1
# Cop supports --auto-correct.
Layout/ElseAlignment:
  Exclude:
    - 'app/controllers/posts_controller.rb'

# Offense count: 1
# Cop supports --auto-correct.
Layout/EmptyLineAfterGuardClause:
  Exclude:
    - 'app/helpers/application_helper.rb'

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: AllowAdjacentOneLineDefs, NumberOfEmptyLines.
Layout/EmptyLineBetweenDefs:
  Exclude:
    - 'app/controllers/users_controller.rb'

# Offense count: 6
# Cop supports --auto-correct.
Layout/EmptyLines:
  Exclude:
    - 'app/controllers/posts_controller.rb'
    - 'app/controllers/users_controller.rb'
    - 'config/routes.rb'
    - 'db/migrate/20200312163752_devise_create_users.rb'
    - 'spec/spec_helper.rb'

# Offense count: 4
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle.
# SupportedStyles: around, only_before
Layout/EmptyLinesAroundAccessModifier:
  Exclude:
    - 'app/channels/chat_room_channel.rb'
    - 'app/controllers/application_controller.rb'
    - 'app/controllers/contacts_controller.rb'
    - 'app/controllers/posts_controller.rb'

# Offense count: 6
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle.
# SupportedStyles: empty_lines, no_empty_lines
Layout/EmptyLinesAroundBlockBody:
  Exclude:
    - 'config/routes.rb'
    - 'db/migrate/20200404073750_create_chat_rooms.rb'
    - 'db/schema.rb'
    - 'spec/controllers/posts_controller_spec.rb'
    - 'spec/models/user_spec.rb'

# Offense count: 8
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle.
# SupportedStyles: empty_lines, empty_lines_except_namespace, empty_lines_special, no_empty_lines, beginning_only, ending_only
Layout/EmptyLinesAroundClassBody:
  Exclude:
    - 'app/controllers/companies_controller.rb'
    - 'app/controllers/pages_controller.rb'
    - 'app/controllers/registrations_controller.rb'
    - 'app/controllers/users_controller.rb'
    - 'app/models/user.rb'

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyleAlignWith, AutoCorrect, Severity.
# SupportedStylesAlignWith: keyword, variable, start_of_line
Layout/EndAlignment:
  Exclude:
    - 'app/controllers/registrations_controller.rb'

# Offense count: 2
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, IndentationWidth.
# SupportedStyles: consistent, consistent_relative_to_receiver, special_for_inner_method_call, special_for_inner_method_call_in_parentheses
Layout/FirstArgumentIndentation:
  Exclude:
    - 'spec/models/post_spec.rb'
    - 'spec/models/user_spec.rb'

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: AllowMultipleStyles, EnforcedHashRocketStyle, EnforcedColonStyle, EnforcedLastArgumentHashStyle.
# SupportedHashRocketStyles: key, separator, table
# SupportedColonStyles: key, separator, table
# SupportedLastArgumentHashStyles: always_inspect, always_ignore, ignore_implicit, ignore_explicit
Layout/HashAlignment:
  Exclude:
    - 'spec/models/user_spec.rb'

# Offense count: 13
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle.
# SupportedStyles: normal, indented_internal_methods
Layout/IndentationConsistency:
  Exclude:
    - 'app/channels/chat_room_channel.rb'
    - 'app/controllers/application_controller.rb'
    - 'app/controllers/contacts_controller.rb'
    - 'spec/models/post_spec.rb'
    - 'spec/models/user_spec.rb'

# Offense count: 43
# Cop supports --auto-correct.
# Configuration parameters: Width, IgnoredPatterns.
Layout/IndentationWidth:
  Enabled: false

# Offense count: 2
# Cop supports --auto-correct.
# Configuration parameters: AllowDoxygenCommentStyle, AllowGemfileRubyComment.
Layout/LeadingCommentSpace:
  Exclude:
    - 'Gemfile'
    - 'config/application.rb'

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, IndentationWidth.
# SupportedStyles: aligned, indented, indented_relative_to_receiver
Layout/MultilineMethodCallIndentation:
  Exclude:
    - 'app/controllers/chat_controller.rb'

# Offense count: 3
# Cop supports --auto-correct.
Layout/SpaceAfterColon:
  Exclude:
    - 'app/mailers/contact_mailer.rb'
    - 'config/routes.rb'
    - 'spec/models/user_spec.rb'

# Offense count: 18
# Cop supports --auto-correct.
Layout/SpaceAfterComma:
  Exclude:
    - 'Gemfile'
    - 'app/controllers/application_controller.rb'
    - 'app/controllers/contacts_controller.rb'
    - 'app/controllers/posts_controller.rb'
    - 'app/mailers/contact_mailer.rb'
    - 'config/routes.rb'
    - 'db/migrate/20200321051742_contact.rb'
    - 'db/migrate/20200327150535_post.rb'
    - 'spec/spec_helper.rb'

# Offense count: 1
# Cop supports --auto-correct.
Layout/SpaceAroundKeyword:
  Exclude:
    - 'spec/spec_helper.rb'

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: AllowForAlignment.
Layout/SpaceBeforeFirstArg:
  Exclude:
    - 'db/migrate/20200325124156_create_posts.rb'

# Offense count: 2
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, EnforcedStyleForEmptyBrackets.
# SupportedStyles: space, no_space, compact
# SupportedStylesForEmptyBrackets: space, no_space
Layout/SpaceInsideArrayLiteralBrackets:
  Exclude:
    - 'config/environments/production.rb'

# Offense count: 9
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle.
# SupportedStyles: final_newline, final_blank_line
Layout/TrailingEmptyLines:
  Exclude:
    - 'Gemfile'
    - 'app/controllers/application_controller.rb'
    - 'app/controllers/contacts_controller.rb'
    - 'app/controllers/registrations_controller.rb'
    - 'app/mailers/contact_mailer.rb'
    - 'config/application.rb'
    - 'config/initializers/locale.rb'
    - 'config/routes.rb'
    - 'spec/models/user_spec.rb'

# Offense count: 24
# Cop supports --auto-correct.
# Configuration parameters: AllowInHeredoc.
Layout/TrailingWhitespace:
  Enabled: false

# Offense count: 1
# Configuration parameters: IgnoredMethods.
Metrics/AbcSize:
  Max: 20

# Offense count: 1
# Configuration parameters: CountComments, ExcludedMethods.
# ExcludedMethods: refine
Metrics/BlockLength:
  Max: 49

# Offense count: 1
# Cop supports --auto-correct.
Style/BlockComments:
  Exclude:
    - 'spec/spec_helper.rb'

# Offense count: 1
# Cop supports --auto-correct.
Style/ColonMethodCall:
  Exclude:
    - 'app/helpers/application_helper.rb'

# Offense count: 48
Style/Documentation:
  Enabled: false

# Offense count: 8
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle.
# SupportedStyles: compact, expanded
Style/EmptyMethod:
  Exclude:
    - 'app/channels/chat_room_channel.rb'
    - 'app/controllers/contacts_controller.rb'
    - 'app/controllers/pages_controller.rb'
    - 'app/controllers/posts_controller.rb'

# Offense count: 3
# Cop supports --auto-correct.
Style/ExpandPathArguments:
  Exclude:
    - 'bin/rails'
    - 'bin/rake'
    - 'bin/rspec'

# Offense count: 93
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle.
# SupportedStyles: always, always_true, never
Style/FrozenStringLiteralComment:
  Enabled: false

# Offense count: 2
# Configuration parameters: MinBodyLength.
Style/GuardClause:
  Exclude:
    - 'app/controllers/contacts_controller.rb'
    - 'app/helpers/application_helper.rb'

# Offense count: 1
# Cop supports --auto-correct.
Style/IfUnlessModifier:
  Exclude:
    - 'app/helpers/application_helper.rb'

# Offense count: 2
Style/MixinUsage:
  Exclude:
    - 'bin/setup'
    - 'bin/update'

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: MinDigits, Strict.
Style/NumericLiterals:
  Exclude:
    - 'db/schema.rb'

# Offense count: 4
# Cop supports --auto-correct.
# Configuration parameters: PreferredDelimiters.
Style/PercentLiteralDelimiters:
  Exclude:
    - 'app/controllers/application_controller.rb'
    - 'app/uploaders/image_uploader.rb'
    - 'config/routes.rb'

# Offense count: 1
# Cop supports --auto-correct.
Style/RedundantBegin:
  Exclude:
    - 'bin/yarn'

# Offense count: 2
# Cop supports --auto-correct.
Style/StderrPuts:
  Exclude:
    - 'bin/yarn'

# Offense count: 79
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, ConsistentQuotesInMultiline.
# SupportedStyles: single_quotes, double_quotes
Style/StringLiterals:
  Exclude:
    - 'Gemfile'
    - 'app/controllers/posts_controller.rb'
    - 'app/controllers/users_controller.rb'
    - 'app/mailers/contact_mailer.rb'
    - 'bin/yarn'
    - 'config/environments/production.rb'
    - 'config/puma.rb'
    - 'config/routes.rb'
    - 'db/migrate/20200312163752_devise_create_users.rb'
    - 'db/migrate/20200312232723_add_name_to_user.rb'
    - 'db/schema.rb'
    - 'spec/models/post_spec.rb'
    - 'spec/models/user_spec.rb'
    - 'spec/rails_helper.rb'

# Offense count: 3
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, MinSize.
# SupportedStyles: percent, brackets
Style/SymbolArray:
  Exclude:
    - 'Gemfile'
    - 'app/controllers/application_controller.rb'
    - 'app/controllers/contacts_controller.rb'

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: IgnoredMethods.
# IgnoredMethods: respond_to, define_method
Style/SymbolProc:
  Exclude:
    - 'db/migrate/20200404073750_create_chat_rooms.rb'

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyleForMultiline.
# SupportedStylesForMultiline: comma, consistent_comma, no_comma
Style/TrailingCommaInArguments:
  Exclude:
    - 'spec/models/post_spec.rb'

# Offense count: 72
# Cop supports --auto-correct.
# Configuration parameters: AutoCorrect, AllowHeredoc, AllowURI, URISchemes, IgnoreCopDirectives, IgnoredPatterns.
# URISchemes: http, https
Layout/LineLength:
  Max: 154
